### ISSUE TITLE
Landing page (Unauthenticated)

### ISSUE THREAD

**Issue by jrob8577** [sfsu-csc-667-spring-2021-roberts/term-project-team-g-dprj#1]
This page will be displayed at the root of the website, and will include an introduction or title, a sign in form, and a link to a registration form.

**URL:** `/`
**Route:** `/routes/unauthenticated/home.js`
**View:** `/views/unauthenticated/home.pug`

**Comment by dbenavi5** [comment]
already created home.js and home.pug files under g-branch
