### ISSUE TITLE
Registration page (Unauthenticated)

### ISSUE THREAD

**Issue by jrob8577** [sfsu-csc-667-spring-2021-roberts/term-project-team-g-dprj#2]
This page will include the registration form, with a link back to the landing page (so that a user can go back and sign in if they did not mean to go to the registration page).

**URL:** `/register`
**Route:** `/routes/unauthenticated/register.js`
**View:** `/views/unauthenticated/register.pug`

**Comment by dbenavi5** [comment]
already created a register.pug and a route for register.js. Will change action in the form to redirect page to landing page(main lobby page)
